//! Content layer (SPEC §4): the file tree under `~/.haven/<project>/`, artifact
//! registration (typed pointer + file copy + sha256), `note` (free scratch, no
//! DB row), and the deterministic `backlog.md` projection.
//!
//! `Store::content_root()` is the `~/.haven` root; per-project content lives at
//! `<root>/<project-key>/`, and artifact `path`s are stored relative to that.

use std::fmt::Write as _;
use std::path::PathBuf;

use rusqlite::params;
use sha2::{Digest, Sha256};

use crate::error::{HavenError, Result};
use crate::model::*;

use super::{new_uuid, ItemFilter, Store};

/// The canonical filename of a context-pack artifact. `create-context-pack` writes
/// it as a `spec` artifact on a group's container; the pack-pointer derivation
/// (HV-75) reads it. This string is the contract between the skill and the store
/// — keep them in sync.
pub const CONTEXT_PACK_ARTIFACT: &str = "context-pack.md";

/// Parameters for `artifact add`.
#[derive(Debug, Default, Clone)]
pub struct NewArtifact {
    pub role: ArtifactRole,
    pub kind: ArtifactKind,
    /// Source file to copy into the content tree (kind = file).
    pub file: Option<PathBuf>,
    /// Inline content to materialize into a file (kind = file). The content
    /// channel for filesystem-less clients: the bytes are written to a file in
    /// the content tree and only the typed pointer is stored in the DB — the
    /// content itself is never a DB column.
    pub content: Option<String>,
    /// Target filename for inline `content` (defaults to `<role>.md`).
    pub name: Option<String>,
    pub uri: Option<String>,
    pub title: Option<String>,
    pub excerpt: Option<String>,
    pub from_owner: Option<OwnerKind>,
    pub to_owner: Option<OwnerKind>,
    pub created_by: Option<String>,
}

/// The bytes (as text) behind an artifact, returned by `artifact get`.
#[derive(Debug, Clone, serde::Serialize)]
pub struct ArtifactContent {
    pub node_ref: String,
    pub role: ArtifactRole,
    pub path: Option<String>,
    pub uri: Option<String>,
    pub content: Option<String>,
}

// These enums are generated by the `sql_enum!` macro (model.rs), which doesn't
// emit `#[derive(Default)]`; the manual impls give `NewArtifact: Default` a
// sensible role/kind. `derivable_impls` is allowed because the macro can't carry
// a `#[default]` variant marker.
#[allow(clippy::derivable_impls)]
impl Default for ArtifactRole {
    fn default() -> Self {
        ArtifactRole::Scratch
    }
}
#[allow(clippy::derivable_impls)]
impl Default for ArtifactKind {
    fn default() -> Self {
        ArtifactKind::File
    }
}

impl Store {
    /// Absolute path to a project's content directory (`<root>/<key>/`).
    fn project_dir(&self, project_key: &str) -> PathBuf {
        self.content_root().join(project_key)
    }

    /// Derive the context pack governing a leaf (HV-75): the LIVE grouping
    /// containers it belongs to that carry a `spec` [`CONTEXT_PACK_ARTIFACT`],
    /// deduped by container. Returns `(pack, clash)` of which at most one is
    /// `Some` — zero containers → `(None, None)`; exactly one → the pack; more
    /// than one → a clash (the conflicting container refs). Pure read: the
    /// pointer is never stored, so the graph stays the single source of truth.
    /// Dedup by container means a re-prepped group (which appends a second
    /// `context-pack.md` row on the *same* container) is not read as a clash.
    pub(crate) fn context_pack_for_node(
        &self,
        node_id: i64,
    ) -> Result<(Option<ContextPack>, Option<Vec<String>>)> {
        let mut stmt = self.conn.prepare(
            "SELECT DISTINCT c.ref
               FROM grouping_edges ge
               JOIN nodes c ON c.id = ge.group_id
               JOIN artifacts a ON a.node_id = c.id
              WHERE ge.member_id = ?1
                AND a.role = 'spec'
                AND a.path LIKE '%/' || ?2
                AND c.status NOT IN ('archived', 'superseded')
              ORDER BY c.ref",
        )?;
        let containers: Vec<String> = stmt
            .query_map(params![node_id, CONTEXT_PACK_ARTIFACT], |r| {
                r.get::<_, String>(0)
            })?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        Ok(match containers.len() {
            0 => (None, None),
            1 => (
                Some(ContextPack {
                    container: containers.into_iter().next().expect("len == 1"),
                    artifact: CONTEXT_PACK_ARTIFACT.to_string(),
                }),
                None,
            ),
            _ => (None, Some(containers)),
        })
    }

    /// Public entry to [`Self::context_pack_for_node`] by selector — used by the
    /// CLI and by `create-context-pack`'s clash precondition.
    pub fn context_pack_for(
        &self,
        project: Option<&str>,
        selector: &str,
    ) -> Result<(Option<ContextPack>, Option<Vec<String>>)> {
        let (project_id, _key) = self.require_project(project)?;
        let node_id = self.resolve_node_id(project_id, selector)?;
        self.context_pack_for_node(node_id)
    }

    /// Register an artifact on a node. For `kind = file`, the content is written
    /// into `items/<ref>/` (or `items/<ref>/notes/` for handoffs) and its sha256
    /// recorded — from either a source `file` (copied) or inline `content` (the
    /// content channel for filesystem-less clients). The bytes live as a file;
    /// the DB stores only the typed pointer.
    pub fn add_artifact(
        &self,
        project: Option<&str>,
        selector: &str,
        new: NewArtifact,
    ) -> Result<Artifact> {
        let (project_id, project_key) = self.require_project(project)?;
        let node_id = self.resolve_node_id(project_id, selector)?;
        let node_ref = self.node_ref(node_id)?;

        if new.role == ArtifactRole::Handoff && (new.from_owner.is_none() || new.to_owner.is_none())
        {
            return Err(HavenError::Invalid(
                "a handoff artifact must carry --from and --to".into(),
            ));
        }

        let (rel_path, content_hash) = match new.kind {
            ArtifactKind::File => {
                if new.file.is_some() && new.content.is_some() {
                    return Err(HavenError::Invalid(
                        "provide either a source --file or inline --content, not both".into(),
                    ));
                }
                // Resolve (filename, bytes) from whichever source was given.
                let (filename, bytes) = if let Some(content) = &new.content {
                    let name = new
                        .name
                        .clone()
                        .unwrap_or_else(|| format!("{}.md", new.role.as_str()));
                    (name, content.clone().into_bytes())
                } else if let Some(src) = &new.file {
                    let bytes = std::fs::read(src).map_err(|e| {
                        HavenError::Invalid(format!("cannot read {}: {e}", src.display()))
                    })?;
                    let filename = src
                        .file_name()
                        .ok_or_else(|| HavenError::Invalid("source has no file name".into()))?
                        .to_string_lossy()
                        .to_string();
                    (filename, bytes)
                } else {
                    return Err(HavenError::Invalid(
                        "a file artifact requires --file <path> or inline --content".into(),
                    ));
                };
                // Filename must be a single plain component (no separators / `..`),
                // so a client-supplied name can't escape the item directory.
                if filename.is_empty()
                    || filename.contains('/')
                    || filename.contains('\\')
                    || filename.split(['/', '\\']).any(|seg| seg == "..")
                    || filename == ".."
                {
                    return Err(HavenError::Invalid(format!(
                        "artifact file name {filename:?} must be a plain file name"
                    )));
                }
                // Handoffs live under notes/; everything else directly in the item dir.
                let subdir = if new.role == ArtifactRole::Handoff {
                    format!("items/{node_ref}/notes")
                } else {
                    format!("items/{node_ref}")
                };
                let dest_dir = self.project_dir(&project_key).join(&subdir);
                std::fs::create_dir_all(&dest_dir)?;
                let dest = dest_dir.join(&filename);
                std::fs::write(&dest, &bytes)?;
                let hash = hex(&Sha256::digest(&bytes));
                (Some(format!("{subdir}/{filename}")), Some(hash))
            }
            ArtifactKind::External | ArtifactKind::Delivery => {
                if new.uri.is_none() {
                    return Err(HavenError::Invalid(
                        "an external artifact requires --uri".into(),
                    ));
                }
                (None, None)
            }
        };

        let public_id = new_uuid();
        self.conn.execute(
            "INSERT INTO artifacts
               (public_id, node_id, role, kind, path, uri, title, excerpt,
                from_owner, to_owner, content_hash, created_by, client_id)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)",
            params![
                public_id,
                node_id,
                new.role,
                new.kind,
                rel_path,
                new.uri,
                new.title,
                new.excerpt,
                new.from_owner,
                new.to_owner,
                content_hash,
                new.created_by,
                new_uuid(),
            ],
        )?;
        let id = self.conn.last_insert_rowid();
        let artifacts = self.load_artifacts(node_id)?;
        artifacts
            .into_iter()
            .find(|a| a.id == id)
            .ok_or_else(|| HavenError::NotFound("artifact just inserted".into()))
    }

    pub fn list_artifacts(
        &self,
        project: Option<&str>,
        selector: &str,
        role: Option<ArtifactRole>,
    ) -> Result<Vec<Artifact>> {
        let (project_id, _) = self.require_project(project)?;
        let node_id = self.resolve_node_id(project_id, selector)?;
        let mut artifacts = self.load_artifacts(node_id)?;
        if let Some(role) = role {
            artifacts.retain(|a| a.role == role);
        }
        Ok(artifacts)
    }

    /// Read an artifact's content. Resolves by `path` if given, else the latest
    /// artifact of `role`. For `kind = file`, reads the local file; when the
    /// file is absent but the row carries a `remote_path` (a synced copy in
    /// cloud Storage), this returns [`HavenError::ContentNotLocal`] so a
    /// sync-aware front-end can lazy-download and retry (SPEC §5).
    pub fn get_artifact(
        &self,
        project: Option<&str>,
        selector: &str,
        role: Option<ArtifactRole>,
        path: Option<&str>,
    ) -> Result<ArtifactContent> {
        let (project_id, project_key) = self.require_project(project)?;
        let node_id = self.resolve_node_id(project_id, selector)?;
        let node_ref = self.node_ref(node_id)?;
        let artifacts = self.load_artifacts(node_id)?;

        let chosen = if let Some(path) = path {
            artifacts
                .into_iter()
                .find(|a| a.path.as_deref() == Some(path))
        } else if let Some(role) = role {
            // Latest of that role (load_artifacts is id-ascending).
            artifacts.into_iter().rfind(|a| a.role == role)
        } else {
            artifacts.into_iter().next_back()
        }
        .ok_or_else(|| HavenError::NotFound(format!("artifact on {node_ref:?}")))?;

        let content = match &chosen.path {
            Some(rel) => {
                let base = self.project_dir(&project_key);
                let full = base.join(rel);
                // Guard against a tampered `path` row escaping the project tree.
                if !full.starts_with(&base) {
                    return Err(HavenError::Invalid(format!(
                        "artifact path {rel:?} escapes the project directory"
                    )));
                }
                match std::fs::read_to_string(&full) {
                    Ok(text) => Some(text),
                    // Missing locally but synced to Storage → a typed signal the
                    // front-ends catch to lazy-download, then retry the read.
                    Err(_) if chosen.remote_path.is_some() && !full.exists() => {
                        return Err(HavenError::ContentNotLocal {
                            project: project_key,
                            rel_path: rel.clone(),
                            remote_path: chosen.remote_path.expect("checked is_some"),
                            content_hash: chosen.content_hash,
                        });
                    }
                    Err(e) => {
                        return Err(HavenError::NotFound(format!(
                            "content file {} not present locally: {e}",
                            full.display()
                        )));
                    }
                }
            }
            None => None,
        };

        Ok(ArtifactContent {
            node_ref,
            role: chosen.role,
            path: chosen.path,
            uri: chosen.uri,
            content,
        })
    }

    /// Append a free-text scratch line to the node's dated notes file. No DB row
    /// (the `notes/` folder is a free filesystem, SPEC §4).
    pub fn note(&self, project: Option<&str>, selector: &str, text: &str) -> Result<PathBuf> {
        let (project_id, project_key) = self.require_project(project)?;
        let node_id = self.resolve_node_id(project_id, selector)?;
        let node_ref = self.node_ref(node_id)?;

        let (y, m, d) = crate::time::today_ymd();
        let dir = self
            .project_dir(&project_key)
            .join(format!("items/{node_ref}/notes"));
        std::fs::create_dir_all(&dir)?;
        let file = dir.join(format!("{y:04}-{m:02}-{d:02}.md"));

        use std::io::Write as _;
        let mut f = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&file)?;
        writeln!(f, "- {text}")?;
        Ok(file)
    }

    /// Regenerate the project's deterministic `backlog.md` projection.
    /// Read-only output, diffable in a vault — never hand-edited (SPEC §4).
    pub fn render(&self, project: Option<&str>) -> Result<PathBuf> {
        let (_project_id, project_key) = self.require_project(project)?;
        let proj = self.get_project(&project_key)?;
        let md = self.backlog_markdown(&project_key, &proj.title)?;

        let dir = self.project_dir(&project_key);
        std::fs::create_dir_all(&dir)?;
        let path = dir.join("backlog.md");
        std::fs::write(&path, md)?;
        Ok(path)
    }

    /// Build the backlog markdown (split out for testing without touching disk).
    pub fn backlog_markdown(&self, project_key: &str, title: &str) -> Result<String> {
        let committed = self.list_items(
            Some(project_key),
            &ItemFilter {
                committed: Some(true),
                ..Default::default()
            },
        )?;
        let icebox = self.list_items(
            Some(project_key),
            &ItemFilter {
                icebox: true,
                ..Default::default()
            },
        )?;

        let mut out = String::new();
        let _ = writeln!(out, "# {title} ({project_key})\n");
        let _ = writeln!(out, "_Generated by `haven render`. Do not hand-edit._\n");

        let _ = writeln!(out, "## Committed\n");
        if committed.is_empty() {
            let _ = writeln!(out, "_(none)_\n");
        } else {
            for item in &committed {
                out.push_str(&self.backlog_line(item)?);
            }
            out.push('\n');
        }

        let _ = writeln!(out, "## Icebox\n");
        if icebox.is_empty() {
            let _ = writeln!(out, "_(none)_\n");
        } else {
            for item in &icebox {
                out.push_str(&self.backlog_line(item)?);
            }
        }
        Ok(out)
    }

    fn backlog_line(&self, item: &Item) -> Result<String> {
        let owner = item
            .owner_kind
            .map(|o| format!(", {o}"))
            .unwrap_or_default();
        let pri = item.priority.map(|p| format!(" P{p}")).unwrap_or_default();
        let edges = self.load_edges(item.id)?;
        let blocked = if edges.depends_on.is_empty() {
            String::new()
        } else {
            format!(" — blocked by: {}", edges.depends_on.join(", "))
        };
        Ok(format!(
            "- `{r}`{pri} {title} ({status}{owner}){blocked}\n",
            r = item.reference,
            title = item.title,
            status = item.status,
        ))
    }
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        let _ = write!(s, "{b:02x}");
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::NewItem;

    fn store_with_root(root: &std::path::Path) -> Store {
        let s = Store::open_in_memory_at(root).unwrap();
        s.add_project("haven", Some("HV"), "Haven", None).unwrap();
        s.use_project("haven").unwrap();
        s
    }

    #[test]
    fn artifact_file_roundtrip_and_hash() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        let item = s
            .add_item(
                None,
                NewItem {
                    title: "Spec work".into(),
                    ..Default::default()
                },
            )
            .unwrap();

        // A source file to register.
        let src = tmp.path().join("spec.md");
        std::fs::write(&src, b"# Spec\nhello\n").unwrap();

        let art = s
            .add_artifact(
                None,
                &item.reference,
                NewArtifact {
                    role: ArtifactRole::Spec,
                    kind: ArtifactKind::File,
                    file: Some(src.clone()),
                    ..Default::default()
                },
            )
            .unwrap();
        assert_eq!(art.role, ArtifactRole::Spec);
        assert_eq!(art.path.as_deref(), Some("items/HV-1/spec.md"));
        assert!(art.content_hash.is_some());

        // The file was copied into the content tree.
        let copied = tmp.path().join("haven/items/HV-1/spec.md");
        assert!(copied.exists());

        // get_artifact reads it back.
        let got = s
            .get_artifact(None, &item.reference, Some(ArtifactRole::Spec), None)
            .unwrap();
        assert_eq!(got.content.as_deref(), Some("# Spec\nhello\n"));
    }

    #[test]
    fn context_pack_for_derives_found_clash_and_dedups() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        let add_phase = |title: &str| {
            s.add_item(
                None,
                NewItem {
                    title: title.into(),
                    node_type: Some(NodeType::Phase),
                    ..Default::default()
                },
            )
            .unwrap()
            .reference
        };
        let pack_on = |container: &str, body: &str| {
            s.add_artifact(
                None,
                container,
                NewArtifact {
                    role: ArtifactRole::Spec,
                    content: Some(body.into()),
                    name: Some(CONTEXT_PACK_ARTIFACT.into()),
                    ..Default::default()
                },
            )
            .unwrap();
        };

        let batch_a = add_phase("Batch A");
        let leaf = s
            .add_item(
                None,
                NewItem {
                    title: "leaf".into(),
                    ..Default::default()
                },
            )
            .unwrap()
            .reference;
        s.group(None, &batch_a, &leaf, false).unwrap();

        // Grouped, but no pack on the container yet → nothing to point at.
        let (pack, clash) = s.context_pack_for(None, &leaf).unwrap();
        assert!(pack.is_none() && clash.is_none());

        // A pack on the one container → Found, pointing at it.
        pack_on(&batch_a, "# pack");
        let (pack, clash) = s.context_pack_for(None, &leaf).unwrap();
        assert_eq!(pack.unwrap().container, batch_a);
        assert!(clash.is_none());

        // Re-prepping appends a SECOND context-pack.md row on the SAME
        // container — dedup by container means it stays one pack, never a clash.
        pack_on(&batch_a, "# pack v2");
        let (pack, clash) = s.context_pack_for(None, &leaf).unwrap();
        assert!(
            pack.is_some() && clash.is_none(),
            "duplicate pack rows on one container must not read as a clash"
        );

        // A SECOND container also claiming the leaf, with its own pack → clash,
        // and no silent pick of either.
        let batch_b = add_phase("Batch B");
        s.group(None, &batch_b, &leaf, false).unwrap();
        pack_on(&batch_b, "# pack b");
        let (pack, clash) = s.context_pack_for(None, &leaf).unwrap();
        assert!(pack.is_none(), "a clash must not silently pick a pack");
        let mut refs = clash.unwrap();
        refs.sort();
        let mut want = vec![batch_a, batch_b];
        want.sort();
        assert_eq!(refs, want);
    }

    #[test]
    fn missing_file_signals_content_not_local_only_with_a_remote_copy() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        let item = s
            .add_item(
                None,
                NewItem {
                    title: "Spec work".into(),
                    ..Default::default()
                },
            )
            .unwrap();
        let art = s
            .add_artifact(
                None,
                &item.reference,
                NewArtifact {
                    role: ArtifactRole::Spec,
                    kind: ArtifactKind::File,
                    content: Some("the spec".into()),
                    ..Default::default()
                },
            )
            .unwrap();

        // Delete the local file (simulating a row that arrived via pull).
        std::fs::remove_file(tmp.path().join("haven/items/HV-1/spec.md")).unwrap();

        // No remote copy → plain NotFound, as before.
        let err = s
            .get_artifact(None, &item.reference, Some(ArtifactRole::Spec), None)
            .unwrap_err();
        assert!(matches!(err, HavenError::NotFound(_)));

        // With a remote_path on the row (as a pulled row would carry) → the
        // typed signal a sync-aware front-end catches to lazy-download.
        s.conn
            .execute(
                "UPDATE artifacts SET remote_path = 'u/haven/items/HV-1/spec.md'
                 WHERE public_id = ?1",
                [&art.public_id],
            )
            .unwrap();
        let err = s
            .get_artifact(None, &item.reference, Some(ArtifactRole::Spec), None)
            .unwrap_err();
        match err {
            HavenError::ContentNotLocal {
                project,
                rel_path,
                remote_path,
                content_hash,
            } => {
                assert_eq!(project, "haven");
                assert_eq!(rel_path, "items/HV-1/spec.md");
                assert_eq!(remote_path, "u/haven/items/HV-1/spec.md");
                assert_eq!(content_hash, art.content_hash);
            }
            other => panic!("expected ContentNotLocal, got {other:?}"),
        }
        assert_eq!(err_code_is_stable(), "content_not_local");
    }

    fn err_code_is_stable() -> &'static str {
        HavenError::ContentNotLocal {
            project: String::new(),
            rel_path: String::new(),
            remote_path: String::new(),
            content_hash: None,
        }
        .code()
    }

    #[test]
    fn inline_content_materializes_a_file() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        let item = s
            .add_item(
                None,
                NewItem {
                    title: "Spec work".into(),
                    ..Default::default()
                },
            )
            .unwrap();

        // Write via the content channel — no source file on disk.
        let art = s
            .add_artifact(
                None,
                &item.reference,
                NewArtifact {
                    role: ArtifactRole::Spec,
                    kind: ArtifactKind::File,
                    content: Some("# Spec\nwritten inline\n".into()),
                    ..Default::default()
                },
            )
            .unwrap();
        // Default filename is <role>.md; the server created the file.
        assert_eq!(art.path.as_deref(), Some("items/HV-1/spec.md"));
        assert!(art.content_hash.is_some());
        assert!(tmp.path().join("haven/items/HV-1/spec.md").exists());

        // Read it back through the same content field.
        let got = s
            .get_artifact(None, &item.reference, Some(ArtifactRole::Spec), None)
            .unwrap();
        assert_eq!(got.content.as_deref(), Some("# Spec\nwritten inline\n"));

        // A custom name is honoured.
        let named = s
            .add_artifact(
                None,
                &item.reference,
                NewArtifact {
                    role: ArtifactRole::Research,
                    kind: ArtifactKind::File,
                    content: Some("notes".into()),
                    name: Some("findings.md".into()),
                    ..Default::default()
                },
            )
            .unwrap();
        assert_eq!(named.path.as_deref(), Some("items/HV-1/findings.md"));

        // file + content together is rejected; a traversal name is rejected.
        let both = s.add_artifact(
            None,
            &item.reference,
            NewArtifact {
                role: ArtifactRole::Scratch,
                kind: ArtifactKind::File,
                content: Some("x".into()),
                file: Some(tmp.path().join("anything.md")),
                ..Default::default()
            },
        );
        assert!(both.is_err());
        let evil = s.add_artifact(
            None,
            &item.reference,
            NewArtifact {
                role: ArtifactRole::Scratch,
                kind: ArtifactKind::File,
                content: Some("x".into()),
                name: Some("../escape.md".into()),
                ..Default::default()
            },
        );
        assert_eq!(evil.unwrap_err().code(), "invalid");
    }

    #[test]
    fn handoff_requires_from_and_to() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        let item = s
            .add_item(
                None,
                NewItem {
                    title: "Work".into(),
                    ..Default::default()
                },
            )
            .unwrap();
        let src = tmp.path().join("h.md");
        std::fs::write(&src, b"handoff").unwrap();

        let err = s
            .add_artifact(
                None,
                &item.reference,
                NewArtifact {
                    role: ArtifactRole::Handoff,
                    kind: ArtifactKind::File,
                    file: Some(src.clone()),
                    ..Default::default()
                },
            )
            .unwrap_err();
        assert_eq!(err.code(), "invalid");

        // With from/to it succeeds and lands under notes/.
        let art = s
            .add_artifact(
                None,
                &item.reference,
                NewArtifact {
                    role: ArtifactRole::Handoff,
                    kind: ArtifactKind::File,
                    file: Some(src),
                    from_owner: Some(OwnerKind::Ai),
                    to_owner: Some(OwnerKind::Human),
                    ..Default::default()
                },
            )
            .unwrap();
        assert_eq!(art.path.as_deref(), Some("items/HV-1/notes/h.md"));
        assert_eq!(art.from_owner, Some(OwnerKind::Ai));
    }

    #[test]
    fn external_artifact_needs_uri_no_file() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        let item = s
            .add_item(
                None,
                NewItem {
                    title: "Research".into(),
                    ..Default::default()
                },
            )
            .unwrap();
        let art = s
            .add_artifact(
                None,
                &item.reference,
                NewArtifact {
                    role: ArtifactRole::Source,
                    kind: ArtifactKind::External,
                    uri: Some("obsidian://vault/note".into()),
                    title: Some("Field notes".into()),
                    ..Default::default()
                },
            )
            .unwrap();
        assert_eq!(art.kind, ArtifactKind::External);
        assert!(art.path.is_none());
        assert_eq!(art.uri.as_deref(), Some("obsidian://vault/note"));
    }

    #[test]
    fn note_appends_without_db_row() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        let item = s
            .add_item(
                None,
                NewItem {
                    title: "Scratch".into(),
                    ..Default::default()
                },
            )
            .unwrap();
        let f = s.note(None, &item.reference, "first thought").unwrap();
        s.note(None, &item.reference, "second thought").unwrap();
        let body = std::fs::read_to_string(&f).unwrap();
        assert!(body.contains("first thought") && body.contains("second thought"));
        // No artifact row was created.
        assert!(s
            .list_artifacts(None, &item.reference, None)
            .unwrap()
            .is_empty());
    }

    #[test]
    fn backlog_markdown_is_deterministic() {
        let tmp = tempfile::tempdir().unwrap();
        let s = store_with_root(tmp.path());
        s.add_item(
            None,
            NewItem {
                title: "Ship it".into(),
                commit: true,
                priority: Some(0),
                status: Some(Status::Ready),
                done_looks_like: Some("shipped".into()),
                ..Default::default()
            },
        )
        .unwrap();
        let dep = s
            .add_item(
                None,
                NewItem {
                    title: "Prereq".into(),
                    commit: true,
                    ..Default::default()
                },
            )
            .unwrap();
        s.add_item(
            None,
            NewItem {
                title: "Blocked".into(),
                commit: true,
                depends_on: Some(dep.reference.clone()),
                ..Default::default()
            },
        )
        .unwrap();
        s.add_item(
            None,
            NewItem {
                title: "Someday".into(),
                ..Default::default()
            },
        )
        .unwrap();

        let a = s.backlog_markdown("haven", "Haven").unwrap();
        let b = s.backlog_markdown("haven", "Haven").unwrap();
        assert_eq!(a, b, "render must be deterministic");
        assert!(a.contains("## Committed"));
        assert!(a.contains("## Icebox"));
        assert!(a.contains("Someday"));
        assert!(a.contains("blocked by: HV-2"));

        // render() writes the file.
        let path = s.render(None).unwrap();
        assert!(path.ends_with("haven/backlog.md"));
        assert_eq!(std::fs::read_to_string(&path).unwrap(), a);
    }
}
